# This is a basic workflow to help you get started with Actions

name: check linked account

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request_target:
    types: [opened, reopened, closed]

permissions:
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: check linked account
        id: check_linked_account
        uses: cssjpn/blog-gh-actions/check-linked-account@6a4d907
        with:
          githubId: "watahani"
          token: ${{ secrets.JPCSSBLOG_DEV_TOKEN }}
      
      - name: deploy preview
        if: steps.check_linked_account.outputs.isLinked == 'true'
        run:
          echo "linked"          
      - name: if tool
        if: steps.check_linked_account.outputs.isLinked != 'true'
        run:
          echo "not linked"          
