# This is a basic workflow to help you get started with Actions

name: get token

# Controls when the workflow will run
on:
  schedule:
    - cron: '52 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get JPCSSBlogDev Token
        id: jpcssblogdev
        uses: ./.github/actions/jpcssblogdev-token/

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}        
      # Runs a single command using the runners shell
      - name: Store token to Secrets
        env:
          TOKEN: ${{ steps.jpcssblogdev.outputs.token }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          REPOSITORY: ${{ github.event.repository.full_name }}
          DEBUG: ${{ toJSON( github.event ) }}
        run: |
          echo "$EVENT"
          gh secret set JPCSSBLOG_DEV_TOKEN --body "$TOKEN" -R "$REPOSITORY"
      - name: check linked account
        id: check_linked_account
        uses: ./.github/actions/check-linked-account/
        with:
          githubId: "watahani"
          token: ${{ secrets.JPCSSBLOG_DEV_TOKEN }}
      
      - name: is fte?
        env:
          isLinked: ${{ steps.check_linked_account.outputs.isLinked }}
        run: |
          echo "is linked: ${isLinked}"
      - name: if tool
        if: steps.check_linked_account.outputs.isLinked == 'true'
        run:
          echo "linked"          
      - name: if tool
        if: steps.check_linked_account.outputs.isLinked != 'true'
        run:
          echo "not linked"          
